// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/com/example/grpc/server/greeter/greeter.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.grpc.server.greeter;

