// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: proto/com/example/grpc/server/greeter/greeter.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.example.grpc.server.greeter;

@kotlin.jvm.JvmName("-initializehelloRequest")
public inline fun helloRequest(block: com.example.grpc.server.greeter.HelloRequestKt.Dsl.() -> kotlin.Unit): com.example.grpc.server.greeter.Greeter.HelloRequest =
  com.example.grpc.server.greeter.HelloRequestKt.Dsl._create(com.example.grpc.server.greeter.Greeter.HelloRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `HelloRequest`
 */
public object HelloRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.grpc.server.greeter.Greeter.HelloRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.grpc.server.greeter.Greeter.HelloRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.grpc.server.greeter.Greeter.HelloRequest = _builder.build()

    /**
     * `string name = 1 [json_name = "name"];`
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * `string name = 1 [json_name = "name"];`
     */
    public fun clearName() {
      _builder.clearName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.grpc.server.greeter.Greeter.HelloRequest.copy(block: `com.example.grpc.server.greeter`.HelloRequestKt.Dsl.() -> kotlin.Unit): com.example.grpc.server.greeter.Greeter.HelloRequest =
  `com.example.grpc.server.greeter`.HelloRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

